# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

gem 'amazing_print'
gem 'argon2'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'dry-struct'
gem 'dry-types'
gem 'graphql'
gem 'graphql-batch'
gem 'graphql-rails_logger'
gem 'has_unique_attribute', '~> 0.1.2'
gem 'image_processing', '~> 1.2'
gem 'oj'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'pundit'
gem 'rails', '~> 6.1.0'
gem 'seedbank'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'unitwise'

group :development do
  gem 'annotate'
  gem 'listen', '~> 3.3'
  gem 'spring'
end

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
end

group :test do
  gem 'rspec-rails'
end
